config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'workers#index'
  resources :workers
  resources :cars
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :front, class_name: 'User', optional: true
  belongs_to :body,  class_name: 'User', optional: true
  belongs_to :paint, class_name: 'User', optional: true

  validates :car, :name, :number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  
  has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
     @car = Car.new(car_params)
     if @car.save
       redirect_to root_path
     else
       render :new
     end
  end

  def show
    @car = Car.find(params[:id])
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    if @car.update(car_params)
      redirect_to action: :show
    end
  end

  def destroy
    car = Car.find(params[:id])
    car.destroy
    redirect_to root_path
  end

  private
  def car_params
    params.require(:car).permit(:car, :number, :price, :name, :date, :front_id, :body_id, :paint_id,:front_date, :body_date, :paint_date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @cars = Car.all
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  def index
    get_week
    @cars = Car.all
  end

  private

  def get_week
    wdays = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']
    @todays_date = Date.today #今日の日付

    @week_days = []  #2  一週間のデータ

    car_plans = Car.where(date: @todays_date..@todays_date + 6)


    7.times do |i|
      today_plans = [] #１  一週間の車のデータ
      car_plans.each do |car|
        today_plans << (car) if car.date == @todays_date + i
      end

      wday_num = @todays_date.wday+i
      if wday_num >= 7
        wday_num = wday_num - 7
      end
      days = { month: (@todays_date + i).month, date: (@todays_date + i).day, car: today_plans, wday: wdays[ wday_num]}

      @week_days<<(days)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/cars/_form.html.erb
<%= form_with model: car,  class: 'form' do |f| %>
    <%= f.label :納車予定日, class: 'lavel' %>
    <%= f.date_field :date, class: 'date-select text-input' %>

    <%= f.label :車種選択, class: 'lavel' %>
    <div class = 'heads-up'>
      *必須
    </div>
    <%= f.text_field :car, class: 'text-input' %>

    <%= f.label :"車両 No", class: 'lavel' %>
    <div class = 'heads-up'>
      *必須
    </div>
    <%= f.text_field :number, class: 'text-input' %>
    
    <%= f.label :お客様名, class: 'lavel' %>
    <div class = 'heads-up'>
      *必須
    </div>
    <%= f.text_field :name, class: 'text-input' %>

    <%= f.label :価格, class: 'lavel' %>
    <%= f.number_field :price, class: 'text-input' %>

    <%= f.label :受付者, class: 'lavel' %>
    <div>着工予定 </div>
    <%= f.date_field :front_date %>
    <%= f.collection_select(:front_id, User.all, :id, :name, {prompt: "担当者を選択してください"}, {class: ' text-input'}) %>

    <%= f.label :鈑金者, class: 'lavel' %>
     <div>業務着工予定 </div>
    <%= f.date_field :body_date %>
    <%= f.collection_select(:body_id, User.all, :id, :name,{prompt: "担当者を選択してください"}, {class: ' text-input'}) %>
    
    <%= f.label :塗装者, class: 'lavel' %>
     <div>着工予定</div>
    <%= f.date_field :paint_date %>
    <%= f.collection_select(:paint_id, User.all, :id, :name,{prompt: "担当者を選択してください"}, {class: ' text-input'}) %>
    
    <div class = 'btn'>
      <%= f.submit '保存' %>
    </div>
<% end %>

app/views/cars/edit.html.erb
<%= render partial: "form",locals: {car: @car}%>

app/views/cars/index.html.erb
<div class="cars">
  <% @cars.each do |car| %>
    <div class="car-list">
      <table border="1" class = "car-list-1">
        <tbody class = "car-list-2" >
          <tr>
            <td colspan="2" class="table-col2 car--table"> <%= link_to car.car, car_path(car.id) %> </td>
          </tr>
          <tr>
            <th class="table-col1">No：</th>
            <td class="table-col2"><%= car.number %></td>
          </tr>
          <tr>
            <th class="table-col1">お客様：</th>
            <td class="table-col2"><%= car.name %></td>
          </tr> 
          <tr>
            <th class="table-col1">納期：</th>
            <% if car.date.present? %>
              <td class="table-col2"><%= car.date.month %>/<%= car.date.day %></td>
            <% end %>
          </tr>
        </tbody>  
      </table>
    </div>
  <% end %>
</div>

app/views/cars/new.html.erb
<%= render partial: "form",locals: {car: @car} %>

app/views/cars/show.html.erb
<div class="car-name">
  <%= @car.car%>
</div>

<div>
    <table border = "1" class="car-table">
      <tbody>
        <tr>
          <th class="table-col1">車両番号</th>
          <td class="table-col2"><%= @car.number %></td>
         </tr>
 
        <tr>
          <th class="table-col1">お客様名</th>
          <td class="table-col2"><%= @car.name %></td>
        </tr>  
           
        <tr>
          <th class="table-col1">フロント担当者</th>
          <% if @car.front.present? %>
            <td class="table-col2">
              <% if @car.front_date.present? %>
                <%= @car.front_date.month %>/<%= @car.front_date.day %>
              <% end %>
              <%= link_to @car.front.name, user_path(@car.front_id) %>
            </td>
          <% end %>
        </tr>
                  
        <tr>
          <th class="table-col1">板金担当者</th>
          <% if @car.body.present? %>
            <td class="table-col2">
              <% if @car.body_date.present? %>
                <%= @car.body_date.month %>/<%= @car.body_date.day %>
              <% end %>
              <%= link_to @car.body.name, user_path(@car.body_id) %>
            </td>
          <% end %>
        </tr>
               
        <tr>
          <th class="table-col1">塗装担当者</th>
          <% if @car.paint.present? %>
            <td class="table-col2">
              <% if @car.paint_date.present? %>
                <%= @car.paint_date.month %>/<%= @car.paint_date.day %>
              <% end %>
              <%= link_to @car.paint.name, user_path(@car.paint_id) %>
            </td>
          <% end %>
        </tr>

        <tr>
           <th class="table-col1">納期</th>
           <% if @car.date.present? %>
              <td class="table-col2"><%= @car.date %></td>
           <% end %>
        </tr>

        <tr>
          <th class="table-col1">金額</th>
          <% if @car.price.present? %>
            <td class="table-col2"><b>¥</b> <%= @car.price %></td>
          <% end %>
        </tr> 
      </tbody>
    </table>
    <div class = "btns">
      <div class = "btn">
        <%= link_to "データ編集", edit_car_path(@car.id), method: :get %>
      </div>
      <div class = 'btn'>
        <%= link_to "データ削除", car_path(@car.id), method: :delete %>
     </div>
     </div>
</div>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
        <div class="header-names">
          <% if user_signed_in? %>
            <div class= "header-name">
              <%= link_to current_user.name, user_path(current_user) %>
            </div>
          <% end %>
          <div class="header-name">
            <%= link_to '納車予定', root_path %>
          </div>   
          <div class="header-name">
            <%= link_to '車種情報を記入', new_car_path %>
          </div>
          <div class="header-name">
            <%= link_to '車両情報', cars_path %>
          </div>
       </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="main"> 
  <div class="inner">
    <div class="user__wrapper">
      <div class="user-name">
        <%= @user.name%>
      </div>
        <table border = "1" class="user_table">
          <tbody>
            <tr>
              <th class="table_1">本日の納車予定の<br>担当した車両</th>
              <td class="table_2">
              <% @cars.each do |car| %>
                <% if @user.id == car.front_id || @user.id == car.body_id || @user.id == car.paint_id%>
                  <% if Date.today == car.date %>
                    <%= link_to car.car, car_path(car.id)%>
                  <% end %>
                <%end %>
              <% end %>
              </td>

           
            </tr>
            <tr>
              <th colspan="2" class="table_1"></th>
              
            </tr>
            <tr>
              <th class="table_1">本日作業予定 </th>
              <td class="table_2">
              <% @cars.each do |car| %>
                <% if @user.id == car.front_id || @user.id == car.body_id || @user.id == car.paint_id%>
                  <% if Date.today == car.front_date || Date.today == car.body_date || Date.today == car.body_date %>
                    <%= link_to car.car, car_path(car.id)%>
                  <% end %>
                <%end %>
              <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      <div class= "log-in">
        <% if current_user.id == @user.id %>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/workers/index.html.erb
<div class = 'main'>
 <div class="side-bar">
    <div class="sides">
       <% User.where.not(id: current_user.id).each do |user| %>
        <div class="side">
          <div class="side-name">
            <%= link_to user.name, user_path(user.id)%> 
          </div>
        </div>
      <% end %> 
    </div>  
  </div>

  <div class='plans'>
  
    <div class = 'price'>
      今月売上　¥
      <% price = 0 %>
      <% @cars.each do |car| %>
        <% if Date.today.month == car.date.month %>
          <% price += car.price  %>
        <% end %>
      <% end %>
      <%= price %>
    </div>

    <h2 class = plans-title>納車予定日</h2>
    <div class= 'plans-data'>
      <% @week_days.each do |day| %>
        <div class='item'>
          <div class='date'>
            <%= day[:month] %>/<%= day[:date] %><%= day[:wday] %>
          </div>
          <ul class='content'>
            <% if day[:car].length != 0 %>
              <% day[:car].each do |car| %>
                <li class='plan-list'>・<%= link_to car.car, car_path(car.id) %></li>
              <% end %>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
</div>